name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Lint and format check
        run: yarn run lint

      - name: Format with prettier
        run: yarn run format
